name: Lint and Test

on:
  workflow_call:
    inputs:
      run_tests:
        description: "Executar testes automatizados"
        required: false
        default: true
        type: boolean
      run_lint:
        description: "Executar análise de estilo (lint)"
        required: false
        default: true
        type: boolean

jobs:
  lint:
    name: Lint (Checkstyle)
    runs-on: ubuntu-latest
    if: ${{ inputs.run_lint }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Executar Checkstyle (lint)
        run: mvn checkstyle:check

  test:
    name: Testes Automatizados
    runs-on: ubuntu-latest
    if: ${{ inputs.run_tests }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Executar testes
        run: mvn test
